cdn_urls:
    stg: "https://objectstorage.us-ashburn-1.oraclecloud.com/n/elqqa/b/magento_extension/o"
    prod: "https://objectstorage.us-ashburn-1.oraclecloud.com/n/elqqa/b/magento_extension/o"

paths:
    build: "builds"
    module: "Bronto"
