# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release-project:
    name: "Release static zip to Github Releases"
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Add HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json
      
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.4
          version: 2
          
      - name: print the repo name
        run: echo ${{ github.repository }}
        
      - name: Generate version
        run: |
           php ci/gen-version.php  > ./version
           ls
           set +o pipefail
           export VERSION="unknown"
           [ -f ./version ] && export VERSION=$(cat ./version)
           echo "VERSION=$VERSION" >> $GITHUB_ENV
           [ -f ./environment ] && export RELEASE_ENV=$(cat ./environment)
           echo "RELEASE_ENV=RELEASE_ENV" >> $GITHUB_ENV
           echo "Printing the env name"
           env
           git status
           echo "Printing env.RELEASE_ENV name"
           echo env.RELEASE_ENV
      - name: Download site Content
        if: ${{ env.RELEASE_ENV }} == 'prod'
        uses: actions/download-artifact@v2
        with:
          name: magento-extension

      - name: Archive Release
        if: ${{ env.RELEASE_ENV }} == 'prod'
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'bronto-magento-module-all-1.0.0'
          path: './pod2'
          exclusions: '*.git* /*vendor/* .editorconfig'
      - name: Create Github Release
        if: ${{ env.RELEASE_ENV }} == 'prod'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
      - name: Verify the files
        run: |
          echo "List the files "
          ls
      - name: Upload Release Asset bronto-magento-module-all
        if: ${{ env.RELEASE_ENV }} == 'prod'
        id: upload-release-asset-bronto-magento-module-all
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./pod2/${{ env.VERSION }}/bronto-magento-module-all-${{ env.VERSION }}.zip
          asset_name: bronto-magento-module-all-${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset bronto-magento-module-browse
        if: ${{ env.RELEASE_ENV }} == 'prod'
        id: upload-release-asset-bronto-magento-module-browse
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./pod2/${{ env.VERSION }}/bronto-magento-module-browse-${{ env.VERSION }}.zip
          asset_name: bronto-magento-module-browse-${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset bronto-magento-module-cart
        if: ${{ env.RELEASE_ENV }} == 'prod'
        id: upload-release-asset-bronto-magento-module-cart
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./pod2/${{ env.VERSION }}/bronto-magento-module-cart-${{ env.VERSION }}.zip
          asset_name: bronto-magento-module-cart-${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset bronto-magento-module-connector
        if: ${{ env.RELEASE_ENV }} == 'prod'
        id: upload-release-asset-bronto-magento-module-connector
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./pod2/${{ env.VERSION }}/bronto-magento-module-connector-${{ env.VERSION }}.zip
          asset_name: bronto-magento-module-connector-${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset bronto-magento-module-contact
        if: ${{ env.RELEASE_ENV }} == 'prod'
        id: upload-release-asset-bronto-magento-module-contact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./pod2/${{ env.VERSION }}/bronto-magento-module-contact-${{ env.VERSION }}.zip
          asset_name: bronto-magento-module-contact-${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset bronto-magento-module-coupon
        if: ${{ env.RELEASE_ENV }} == 'prod'
        id: upload-release-asset-bronto-magento-module-coupon
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./pod2/${{ env.VERSION }}/bronto-magento-module-coupon-${{ env.VERSION }}.zip
          asset_name: bronto-magento-module-coupon-${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset bronto-magento-module-email
        if: ${{ env.RELEASE_ENV }} == 'prod'
        id: upload-release-asset-bronto-magento-module-email
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./pod2/${{ env.VERSION }}/bronto-magento-module-email-${{ env.VERSION }}.zip
          asset_name: bronto-magento-module-email-${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset bronto-magento-module-enterprise
        if: ${{ env.RELEASE_ENV }} == 'prod'
        id: upload-release-asset-bronto-magento-module-enterprise
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./pod2/${{ env.VERSION }}/bronto-magento-module-enterprise-${{ env.VERSION }}.zip
          asset_name: bronto-magento-module-enterprise-${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset 9
        if: ${{ env.RELEASE_ENV }} == 'prod'
        id: upload-release-asset-9
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./pod2/${{ env.VERSION }}/bronto-magento-module-integration-${{ env.VERSION }}.zip
          asset_name: bronto-magento-module-integration-${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset bronto-magento-module-inventory
        if: ${{ env.RELEASE_ENV }} == 'prod'
        id: upload-release-asset-bronto-magento-module-inventory
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./pod2/${{ env.VERSION }}/bronto-magento-module-inventory-${{ env.VERSION }}.zip
          asset_name: bronto-magento-module-inventory-${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset bronto-magento-module-m2
        if: ${{ env.RELEASE_ENV }} == 'prod'
        id: upload-release-asset-bronto-magento-module-m2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./pod2/${{ env.VERSION }}/bronto-magento-module-m2-${{ env.VERSION }}.zip
          asset_name: bronto-magento-module-m2-${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset bronto-magento-module-notification
        if: ${{ env.RELEASE_ENV }} == 'prod'
        id: upload-release-asset-bronto-magento-module-notification
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./pod2/${{ env.VERSION }}/bronto-magento-module-notification-${{ env.VERSION }}.zip
          asset_name: bronto-magento-module-notification-${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset bronto-magento-module-optin
        if: ${{ env.RELEASE_ENV }} == 'prod'
        id: upload-release-asset-bronto-magento-module-optin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./pod2/${{ env.VERSION }}/bronto-magento-module-optin-${{ env.VERSION }}.zip
          asset_name: bronto-magento-module-optin-${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset bronto-magento-module-order
        if: ${{ env.RELEASE_ENV }} == 'prod'
        id: upload-release-asset-bronto-magento-module-order
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./pod2/${{ env.VERSION }}/bronto-magento-module-order-${{ env.VERSION }}.zip
          asset_name: bronto-magento-module-order-${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset bronto-magento-module-product
        if: ${{ env.RELEASE_ENV }} == 'prod'
        id: upload-release-asset-bronto-magento-module-product
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./pod2/${{ env.VERSION }}/bronto-magento-module-product-${{ env.VERSION }}.zip
          asset_name: bronto-magento-module-product-${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset bronto-magento-module-rating
        if: ${{ env.RELEASE_ENV }} == 'prod'
        id: upload-release-asset-bronto-magento-module-rating
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./pod2/${{ env.VERSION }}/bronto-magento-module-rating-${{ env.VERSION }}.zip
          asset_name: bronto-magento-module-rating-${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset bronto-magento-module-redemption
        if: ${{ env.RELEASE_ENV }} == 'prod'
        id: upload-release-asset-bronto-magento-module-redemption
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./pod2/${{ env.VERSION }}/bronto-magento-module-redemption-${{ env.VERSION }}.zip
          asset_name: bronto-magento-module-redemption-${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset package json
        if: ${{ env.RELEASE_ENV }} == 'prod'
        id: upload-release-asset-package-json
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./pod2/packages.json
          asset_name: packages.json
          asset_content_type: application/json
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Add HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json
      
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.4
          version: 2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: php -v
        
      - name: Generate version
        run: |
           php ci/gen-version.php  > ./version
           ls
           set +o pipefail
           export VERSION="unknown"
           [ -f ./version ] && export VERSION=$(cat ./version)
           echo "VERSION=$VERSION" >> $GITHUB_ENV
           [ -f ./environment ] && export RELEASE_ENV=$(cat ./environment)
           echo "RELEASE_ENV=RELEASE_ENV" >> $GITHUB_ENV
           git status
           echo "RELEASE_ENV value"
           echo $RELEASE_ENV
           echo "*******"
           rm ./environment
           
      - name: print the repo name
        run: |
          echo ${{ github.repository }}
          echo ${{ github.repository }}
          echo "${{ env.VERSION }}"
          echo $VERSION
          echo https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          echo "Printing environment variable"
          env
        
      - name: Execute build steps
        run:  php ci/build.php --environment prod --version $VERSION
        
      - name: Check the build version
        run: cd builds/ && ls

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: magento-extension
          path: ./builds/ # or path/to/artifact
          
      - name: Remove auth.json file
        run: rm -f $GITHUB_WORKSPACE/auth.json

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
