# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release-project:
    name: "Release static zip to Github Releases"
    runs-on: ubuntu-latest
    needs: build
    steps:
    
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: print the repo name
        run: echo ${{ github.repository }}
        
      - name: Generate version
        run: |
           php ci/gen-version.php  > ./version
           ls
           set +o pipefail
           export VERSION="unknown"
           [ -f ./version ] && export VERSION=$(cat ./version)
           git checkout $VERSION
           git status
           
      - name: Download site Content
        uses: actions/download-artifact@v2
        with:
          name: magento-extension
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'release.zip'
      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $VERSION
          release_name: Release $VERSION
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./release.zip
          asset_name: magento-extension$VERSION.zip
          asset_content_type: application/zip
      
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Add HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json
      
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.4
          version: 2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: php -v
        
      - name: Generate version
        run: |
           php ci/gen-version.php  > ./version
           ls
           set +o pipefail
           export VERSION="unknown"
           [ -f ./version ] && export VERSION=$(cat ./version)
           echo $VERSION
           git checkout $VERSION
           git status
        
      - name: Execute build steps
        run:  php ci/build.php --environment prod --version $VERSION
        
      - name: Check the build version
        run: cd builds/ && ls

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: magento-extension
          path: ./builds/ # or path/to/artifact
          
      - name: Remove auth.json file
        run: rm -f $GITHUB_WORKSPACE/auth.json

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
